# Docker Compose override for development environment
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  opencbs-server:
    environment:
      # Development-specific overrides
      SPRING_JPA_SHOW_SQL: true
      LOGGING_LEVEL_COM_OPENCBS: DEBUG
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      
      # Use H2 in-memory database for development (optional)
      # Uncomment the following lines to use H2 instead of PostgreSQL
      # SPRING_DATASOURCE_URL: jdbc:h2:mem:opencbs
      # SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      # SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      
      # Enable development features
      OPENCBS_CORE_ENABLEINTERESTACCRUAL: true
      OPENCBS_CORE_ENABLEPENALTYACCRUAL: true
      OPENCBS_CORE_ENABLEAUTOREPAYMENT: false
      DAY_CLOSURE_ENABLE: false
      
      # Development email settings (use mailhog or similar)
      EMAIL_ENABLED: false
      
    volumes:
      # Mount source code for hot reload (if using Spring Boot DevTools)
      - ./server:/workspace:ro
      
    ports:
      # Add debugging port for IDE integration
      - "5005:5005"
    command: >
      java -jar /usr/app/opencbs-server.jar 
      -Djava.security.egd=file:/dev/./urandom 
      -Dspring.config.location=/usr/app/application.properties
      -Dspring.profiles.active=dev
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  # Mailhog for development email testing
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: opencbs-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - opencbs-network

  # Override for faster development database
  postgres:
    environment:
      POSTGRES_DB: opencbs_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      
volumes:
  postgres_dev_data:
    driver: local