# OpenCBS Cloud Server Configuration (YAML format)
# Alternative to application.properties - use either this file OR application.properties, not both
# This file contains all configurable parameters used throughout the OpenCBS system

# OpenCBS Core Module Configuration
opencbs:
  core:
    # Enable/disable automatic interest accrual calculation
    enableInterestAccrual: false
    # Enable/disable automatic penalty accrual calculation  
    enablePenaltyAccrual: false
    # Enable/disable automatic loan repayment processing
    enableAutoRepayment: false

# File Storage Configuration
attachment:
  # Directory path where uploaded attachments will be stored
  location: /var/opencbs/attachments

template:
  # Directory path where document templates are stored  
  location: /var/opencbs/templates

# Message Queue Configuration
spring:
  rabbitmq:
    # RabbitMQ server configuration
    host: localhost
    frontHost: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    directExchange: opencbs.direct
    fanoutExchange: opencbs.fanout
  
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/opencbs_cloud
    username: opencbs
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Account Balance Calculation Configuration
account-balance-calculation:
  exchange: balance.exchange
  queue: balance.calculation.queue
  routingKey: balance.calculation

# Day Closure Configuration
day-closure:
  # Enable automatic start of day closure process
  autoStart: false
  # Time to automatically start day closure (HH:mm format)
  autoStartTime: "23:00"
  # Email addresses to notify in case of day closure errors
  errorToEmails:
    - admin@opencbs.com
    - operations@opencbs.com

# Task Executor Configuration
task-executor:
  # Minimum number of threads in the task executor pool
  minPoolSize: 2
  # Maximum number of threads in the task executor pool
  maxPoolSize: 10

# Email Sender Configuration
email:
  sender: OpenCBS System

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m

# Logging Configuration
logging:
  level:
    root: INFO
    com.opencbs: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# Profile-specific configurations can be created in separate files:
# - application-dev.yml for development profile
# - application-prod.yml for production profile  
# - application-test.yml for testing profile