# Development Profile Configuration
# Use with: --spring.profiles.active=dev

spring:
  datasource:
    url: jdbc:h2:mem:opencbs_dev
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop

opencbs:
  core:
    enableInterestAccrual: true
    enablePenaltyAccrual: true
    enableAutoRepayment: false

attachment:
  location: /tmp/opencbs/attachments

template:
  location: /tmp/opencbs/templates

day-closure:
  autoStart: false
  errorToEmails:
    - developer@opencbs.com

task-executor:
  minPoolSize: 1
  maxPoolSize: 5

logging:
  level:
    com.opencbs: DEBUG