ALTER TABLE tills ADD COLUMN IF NOT EXISTS changed_by_id INTEGER, ADD COLUMN IF NOT EXISTS open_date TIMESTAMP,
  ADD COLUMN IF NOT EXISTS close_date TIMESTAMP;

ALTER TABLE tills
  ADD CONSTRAINT IF NOT EXISTS tills_created_by_id_fkey FOREIGN KEY (changed_by_id) REFERENCES users (id) MATCH FULL;